name: Morning Telegram Message


on:

  workflow_dispatch:

  schedule:
    - cron: "30 3 * * *"


jobs:

  send-message:

    runs-on: ubuntu-latest


    steps:

      - name: دریافت کد
        uses: actions/checkout@v4


      - name: نصب Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: نصب وابستگی‌ها
        run: |
          pip install -r requirements.txt


      - name: اجرای ربات
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
          CHANNEL_LINK: ${{ secrets.CHANNEL_LINK }}

        run: |
          python src/main.py
